version: '3'

services:
  elrond-rosetta-observer-devnet:
    ulimits:
      nproc: 65535
    image: elrond-rosetta:latest
    container_name: elrond-rosetta-observer-devnet
    ports:
      - "${PORT_OBSERVER}:8080"
      - "${PORT_P2P}:37373"
    volumes:
      - ${DATA_FOLDER_OBSERVER}:/data
    env_file:
      - devnet.env
    environment:
      - NETWORK=devnet
      - PROGRAM=node
      - DOWNLOAD_CHAIN_ID=D
    command: --destination-shard-as-observer=${OBSERVER_ACTUAL_SHARD} --log-save --log-level=${LOG_LEVEL} --log-logger-name --rest-api-interface=0.0.0.0:8080 --working-directory=/data --validator-key-pem-file=/data/observerKey.pem --serialize-snapshots --disable-consensus-watchdog
    networks:
      elrond-rosetta-devnet:
        ipv4_address: 11.0.0.10

  elrond-rosetta-online-devnet:
    image: elrond-rosetta:latest
    container_name: elrond-rosetta-online-devnet
    ports:
      - "${PORT_ROSETTA_ONLINE}:8080"
    volumes:
      - ${DATA_FOLDER_ROSETTA_ONLINE}:/data
    environment:
      - NETWORK=devnet
      - PROGRAM=rosetta
    command: --port 8080 --observer-http-url=http://11.0.0.10:8080 --blockchain=${BLOCKCHAIN_NAME} --network-id=D --network-name=devnet --num-shards=3 --observer-actual-shard=${OBSERVER_ACTUAL_SHARD} --observer-projected-shard=${OBSERVER_PROJECTED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --first-historical-epoch=${FIRST_HISTORICAL_EPOCH} --num-historical-epochs=${NUM_HISTORICAL_EPOCHS} --native-currency=EGLD --logs-folder=/data
    networks:
      elrond-rosetta-devnet:
        ipv4_address: 11.0.0.21

  elrond-rosetta-offline-devnet:
    image: elrond-rosetta:latest
    container_name: elrond-rosetta-offline-devnet
    ports:
      - "${PORT_ROSETTA_OFFLINE}:8080"
    volumes:
      - ${DATA_FOLDER_ROSETTA_OFFLINE}:/data
    environment:
      - NETWORK=devnet
      - PROGRAM=rosetta
    command: --port 8080 --offline --observer-http-url=http://nowhere.localhost.local --blockchain=${BLOCKCHAIN_NAME} --network-id=D --network-name=devnet --num-shards=3 --observer-actual-shard=${OBSERVER_ACTUAL_SHARD} --observer-projected-shard=${OBSERVER_PROJECTED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --first-historical-epoch=${FIRST_HISTORICAL_EPOCH} --num-historical-epochs=${NUM_HISTORICAL_EPOCHS} --native-currency=EGLD --logs-folder=/data
    networks:
      elrond-rosetta-devnet:
        ipv4_address: 11.0.0.22

networks:
  elrond-rosetta-devnet:
    ipam:
      config:
        - subnet: 11.0.0.0/24
